### ISSUE TITLE
Page not Found error  in client while run on localhost

### ISSUE THREAD

**Issue by RAzaALy** [strapi/foodadvisor#104]

**Comment by capsloq** [comment]
Did you run `yarn seed` in /api  **before** running  `yarn develop` ?

**Comment by RAzaALy** [comment]
> Did you run `yarn seed` in /api **before** running `yarn develop` ?

Thanks now it's work

**Comment by CorvusGei** [comment]
I have a similar problem.
I try to run Foodadvisor on a K8s-cluster and used the manual from https://strapi.io/blog/deploying-and-scaling-the-official-strapi-demo-app-foodadvisor-with-kubernetes - and use Traefik IngressRoute.
I can access the backend, but at the frontend shows the Strapi icon and Error 404 - page not found. Is there an error in the manual? I'm out of ideas on what else to try.

**Comment by sudheeshcm-zynga** [comment]
I got the same issue. Tried running yarn seed on the /api folder.
Still didn't solve the issue.
Both apps run successfully without any errors but the client fails to load content and returns a 404 error.
