### ISSUE TITLE
Preview Mode provide a example url

### ISSUE THREAD

**Issue by capsloq** [strapi/foodadvisor#105]
I was debugging through the preview mode, especially  `/client/pages/api/preview.js and 
getData(req.query.slug, req.query.locale, req.query.apiID, req.query.kind, true)` but couldn't figure it out.
I am getting through the preview secret check successfully but never into preview mode.
If the preview mode is working in this project, could you please provide a working preview url with all the query parameters given there is a draft in e.g. /pages/draftpage?

**Comment by Mcastres** [comment]
Hello @capsloq 👋 

Considering a `draftpage` page, the preview url would be: `http://localhost:3000/api/preview?secret=ARNFCb9zrC9ZHm5hZzCigWivD40icS4s&slug=draftpage&locale=en&apiID=page&kind=collectionType`

You need to save the content and then having the front-end running :)

**Comment by capsloq** [comment]
@Mcastres  Yep that does work. I must have done something wrong when trying it myself i though it was similar. And thanks for the hint with the running frontend haha ;-)[🔥](https://emojipedia.org/fire/)
