### ISSUE TITLE
Global > Footer includes Shared > FooterColumns but is not selectable

### ISSUE THREAD

**Issue by Thermal-Shock** [strapi/foodadvisor#111]
There appears to be a problem with your demo content type model. 

You have a Shared > FooterColumns that contains a title and then a repeatable component of links (Shared > Link). 

You then have a Global > Footer that appears to include this as a repeatable component, however this is not selectable as an existing component. The "Select a component" even says "Select ..." instead of the component name (e.g. "shared - footercolumn" for example. 

It doesn't appear possible to create a component that includes an existing component that contains a component. 

Yet somehow you've managed to force your demo to allow this. This should not be allowed if the user themselves cannot replicate it.

**Comment by Mcastres** [comment]
Hello @Thermal-Shock 👋 

Using the UI, you can nest 2 components only. However, by directly modifying the json file of the parent component, you can nest way more.
