### ISSUE TITLE
PageNotFound error on client 

### ISSUE THREAD

**Issue by sudheeshcm-zynga** [strapi/foodadvisor#117]
Related Issue: https://github.com/strapi/foodadvisor/issues/104
I got the same issue. Tried running yarn seed on the /api folder.
Still didn't solve the issue.
Both apps run successfully without any errors but the client fails to load content and returns a 404 error.

**Comment by pierreburgy** [comment]
This issue looks to happen only on Node.js 17 and higher:
 - https://stackoverflow.com/questions/71836634/strapi-fetcherror-request-to-http-localhost1337-api-events-failed-reason-c/
 - https://github.com/node-fetch/node-fetch/issues/1624
 
 Could you try to replace `http://localhost:1337` with `http://127.0.0.1:1337` in the `client/.env.development` file?
