### ISSUE TITLE
Missing setup script

### ISSUE THREAD

**Issue by micheleriva** [strapi/foodadvisor#24]
Hi!
I love Strapi and this project seems perfect to understand how that CMS works. I just have a problem with the `api` installation: I have to run `npm run setup --plugins`, but no `setup` script is set in the package.json file.
I am doing something wrong? 🤔 

Thanks!

**Comment by lauriejim** [comment]
Ho sorry, it's an update miss.
We migrated the strapi API to the beta version and this command no longer exist.
I will remove it right now. Thank you for reporting that.
