### ISSUE TITLE
Search input not work

### ISSUE THREAD

**Issue by timeshift92** [strapi/foodadvisor#27]
search in admin pane not work

**Comment by lauriejim** [comment]
Hello, can you give us more details, please.

What did you type in the search bar?
And what did you except?

**Comment by timeshift92** [comment]
Hello, I’ll describe it in stages now,
1. cloned https://github.com/strapi/foodadvisor.git
2. launched all the commands from readme.md
3. registered at http: // localhost: 1337 / admin
4. went here http: // localhost: 1337 / admin / plugins / content-manager / category? Source = content-manager
5. at the top in the search wrote French

Filtering and displaying fields named Frech was expected
but shows all fields

**Comment by timeshift92** [comment]
и еще получается к админ панели имеют доступ только администраторы, даже если я пользователя сделаю администратором он не сможет попасть в админ панель?

**Comment by lauriejim** [comment]
Okay thank you for this report.

**Comment by soupette** [comment]
@timeshift92 we use`sqlite` for the database and currently the search does not work for this particular DB. You can switch it to `mongod` or  another one if you'll like to it work.

**Comment by timeshift92** [comment]
Ok, thanks
