### ISSUE TITLE
Sort restaurants by likes

### ISSUE THREAD

**Issue by davidkofahl** [strapi/foodadvisor#44]
Hi,

After looking through the strapi documentation, there doesn't seem to be a way to sort a query by the properties of a relationship. As an example: sorting restaurants in this demo by either total number of likes or reviews. I know I can tap into knex and send a custom query. Is this the route I should take?

Any guidance would be greatly appreciated. 

Thank you for the time,

**Comment by lauriejim** [comment]
Hello! In Strapi it's possible to filter by relation's field but it will not possible to sort by them.
You are correct, if you want this feature, you will have to create your own API endpoint to manage this query logic.
And to achieve that, you will have to use directly Knex (you are right)
