### ISSUE TITLE
Cant able to login in admin panel

### ISSUE THREAD

**Issue by DineshLt93** [strapi/foodadvisor#51]
Hi,

I have cloned your project and installed it successfully. The front end also working fine. But in backend cant able to login the admin panel getting the _An internal server error occurred_ error. Kindly give me any need full suggestions.

Thanks.

**Comment by vantinhuynh** [comment]
me too

**Comment by mryechkin** [comment]
Having the same issue as well

**Comment by localredhead** [comment]
Drop into the `/api/config/` folder and update `server.js`, swapping the ENV var for JWT secret with a key.

https://github.com/strapi/foodadvisor/commit/16e364dbc9a86e5533e70c023b088ec4856a54a7#diff-7e46daeb55a8ff301e1263fc530afc62R4

**Comment by lauriejim** [comment]
Hello! please check this PR that could fix your issue - https://github.com/strapi/foodadvisor/pull/50
