### ISSUE TITLE
Update Strapi Version from 3.0.6 to 3.2.5

### ISSUE THREAD

**Issue by CtFelix** [strapi/foodadvisor#60]
Hi to every one!
How to update correctly strapi version from 3.0.6 to 3.2.5 witch кeeping current collections of types and data

**Comment by CtFelix** [comment]
Or would it be easier for me to install a clean new version and manually migrate 20 types and 40 values of these types?

**Comment by lauriejim** [comment]
Hello, this already has been done 9 days ago.
Here is the [related PR](https://github.com/strapi/foodadvisor/pull/58).
So I suggest pulling the last version of the `master` branch.
Have a good day.
