### ISSUE TITLE
Missing images in the cloned/running local instance

### ISSUE THREAD

**Issue by vagarwal1968** [strapi/foodadvisor#85]
Hi, I will preface this issue by saying that I am not a coder (anymore). I cloned the git repo and then ran "yarn && yarn run seed && yarn develop" in the API folder. I then set up my admin account and logged in. However, when I go to the media gallery, all the images are missing. 
![screenshot-localhost_1337-2021 08 19-08_58_44](https://user-images.githubusercontent.com/10643532/130081831-a62599c9-c97a-4567-ba88-d2688ed52389.png)
I have deleted everything and started over but with the exact same results. Any ideas on what I can do to fix these issues?

**Comment by vagarwal1968** [comment]
I guess for some reason, the "yarn run seed" command did not do its thing. I found the data.zip file in the root of the api folder and I unzipped the contents of that into [foodadvisorv2]\api\public\uploads and now the images do load up on the client side. In the Strapi admin interface, I see some images but not all in the thumbnails view. I have a lot of missing images. However when I click on one of the missing images, the image does show in the modal. Any ideas on what is going on here?

**Screenshot 1: showing many missing images**
![screenshot-localhost_1337-2021 08 19-22_35_22](https://user-images.githubusercontent.com/10643532/130175331-f1020385-6760-40ca-a9fc-df4d475167e3.png)

**Screenshot 2: I opened the first missing image**
![screenshot-localhost_1337-2021 08 19-22_36_32](https://user-images.githubusercontent.com/10643532/130175344-9c8677ec-3ad5-4bcd-a375-73f961581c96.png)

**Comment by Mcastres** [comment]
Hey @vagarwal1968, thanks for posting this issue.

A new version of this demo is currently being developed on the v2 branch. Feel free to `git checkout v2` ;)
Are you on Windows?

**Comment by vagarwal1968** [comment]
@Mcastres I am on Windows and I am using v2. We also did the v2 install on a Linux distribution with the same results. In fact, I requested a trial for 24 hours, and the server that was provisioned and provided to me had the exact same issue. So, I know it is not me. :)

**Comment by rawzone** [comment]
Can confirm I have the same issue under Linux (No Windows available for testing).

**Comment by Mcastres** [comment]
The seed command might have some issues on Windows and Linux then. It will be hard for me to test it but I'm on it!
However I'm not sure this is happening on live demos @vagarwal1968, I just checked multiple instances and there is no problem on that 🤔

**Comment by vagarwal1968** [comment]
@Mcastres I can assure you that this issue happened in the demo instance that was provisioned for me for 24 hours. :)  And to prove it to myself, I just requested another instance, and sure enough, this new instance (provisioned today) too has the same issue. Page 1 of the media library is fine with 10 items per page. Increase the size to 100 items per page and you will see the issue. See new screenshot from the demo instance provisioned for me.
![Media-Library-Screenshot](https://user-images.githubusercontent.com/10643532/131704268-f1be9259-00c9-458c-ba79-a469b1ebeef6.png)

**Comment by Mcastres** [comment]
In fact, this is weird 🤔 
I will try to know why this is happening! Thanks @vagarwal1968!

**Comment by Mcastres** [comment]
Alright @vagarwal1968, the new commit should fix the issue :) 
Sorry for the inconvenience

**Comment by vagarwal1968** [comment]
Thanks @Mcastres - I verified that the thumbnails show up in the media library now. All I had to do was download the latest data.zip and unzip its contents to api/public/uploads. Closing the issue.
