### ISSUE TITLE
Client error in Foodadvisor V2

### ISSUE THREAD

**Issue by rawzone** [strapi/foodadvisor#86]
Hello,

I'm getting some errors in the client for Foodadvisor V2 when browsing restaurants via this URL / Slug (All the restaurants have the same problem) :

`http://localhost:3000/restaurants/latitude-15-degrees-restaurant?lang=en`

![2021-08-31_11-06](https://user-images.githubusercontent.com/2092357/131476379-47e03c9f-28b7-45da-81c3-0bca6e911f4b.png)

Testing under Linux and normally have no problems developing in NextJS.

**Comment by Mcastres** [comment]
Thanks for posting the issue @rawzone, it has been fixed! Should be working now :)

**Comment by rawzone** [comment]
No problem.
Just want to confirm that its working after a fresh pull of V2.
