### ISSUE TITLE
Basic functionality

### ISSUE THREAD

**Issue by staminna** [strapi/foodadvisor#89]
Hi

Is the demo supposed to reset when you log out?
I was using it as the skeleton to my new site, and when I stop the server and started again, everything was reset to Demo and lost my menus, etc..

Thanks
Jorge

**Comment by Mcastres** [comment]
Hello @staminna 👋 
No, it is not supposed to, unless you run the `yarn seed` command.  This command will remove the database and re-create a new one with the default data.

**Comment by staminna** [comment]
Hi @Mcastres Correct!

Thanks :)
